# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
latex: true
dist: trusty 

env:
  global:
  - _R_CHECK_FORCE_SUGGESTS_=false
  - MAKEFLAGS="-j 2"



r_packages:
  - covr
  - knitr
  
r:
  - oldrel
  - release
  - devel:
    - github_packages:
       - yihui/knitr
       - Rdatatable/data.table


after_success:
  - Rscript -e 'covr::codecov()'

script:
    - R CMD build .
    - R CMD check *tar.gz
    - sh .publish_doc.sh



notifications:
  email:
    on_success: change
    on_failure: change
